name: release management
on:
  push:
    branches:
      - main
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened' ]

permissions: { }

jobs:
  unit-test:
    name: 'Check Quality (unit-test)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout sources'
        uses: 'actions/checkout@v4'

      - name: 'Getting python'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.12'

  release:
    name: 'Release version'
    if: github.ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    needs: [ unit-test ]
    steps:
      - name: 'Checkout sources'
        uses: 'actions/checkout@v4'

      - name: 'Semantic Release'
        uses: 'cycjimmy/semantic-release-action@v4'
        with:
          semantic_version: 24.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.0
            @semantic-release/release-notes-generator@14.0.0
            @semantic-release/changelog@6.0.3
            @semantic-release/github@10.0.5
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
